#servlet配置
server:
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/