#上传路径配置
brightease:
  goldenDragonCsvPath: D:\\home\\data\\goldenDragonCsvPath\\
  ftpZipPath: D:\\home\\data\\futian-csvPath\\

#设置ftp
ftp:
  host: ftp.mgldl.com.cn
  port: 21
  username: mgl
  password: MglAa110
  defatultport: 21
  serverpath: csvfile
  req:
    url: ftp.mgldl.com.cn
