server:
  port: 9523
  servlet:
    context-path: /
spring:
  application:
    name: futian-goldenDragon
  profiles:
    active: '@env@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

#日志生成目录
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.mgl: info
    org.springframework: WARN
    org.spring.springboot.dao: info
  config: classpath:logback-boot.xml
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.mgl.bean.*

