server:
  port: 9528

spring:
  application:
    name: futian-goldenDragon
  profiles:
    active: '@env@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.mgl.bean.*

