#上传路径配置
brightease:
  csvBeiyouPath: d:/server110/test/
  csvNewPath: d:/server110/mytest/
  filePath: d:/
  tempUpLoadPath: d:/
  goldenDragonCsvPath: d:/GoldenDragon/
  ftpZipPath: D:/server110/csv-zip

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mgl_carshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

#ftp
ftp:
  host: ftp.mgldl.com.cn
  port: 21
  username: mgl
  password: MglAa110
  defatultport: 21
  serverpath: csvfile
  req:
    url: ftp.mgldl.com.cn
