#上传路径配置
brightease:
  csvPath: d:/
  filePath: d:/
  tempUpLoadPath: d:/

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mgl_carshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

#ftp
ftp:
  host: 192.168.0.110
  port: 22
  username: root
  password: 1qazXSW@
  defatultport: 22
  serverpath: carsfile
  req:
    url: 192.168.0.110
